# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: continuous integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:

  build-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.in
        pip install -r requirements-dev.in
        pip install -e .
    - uses: actions/upload-artifact@master
      with:
        name: venv
        path: venv/

  linting:
    needs: build-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: venv
        path: venv/
    - name: Linting
      run: |
        pwd
        source venv/bin/activate
        pre-commit install
        pre-commit run --all-files

  unit-tests:
    needs: build-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: venv
        path: venv/
    - name: Unit Tests
      run: |
        source venv/bin/activate
        pytest ./tests/unit/ --doctest-modules --junitxml=junit/unit-test-results.xml --cov=com --cov-report=xml --cov-report=html
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-unit-test-results
        path: junit/unit-test-results.xml
      if: ${{ always() }}  # publish even when some tests fail

  integration-tests:
    needs: build-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: venv
        path: venv/
    - name: Integration Tests
      run: |
        source venv/bin/activate
        pytest ./tests/integration/ --doctest-modules --junitxml=junit/integration-test-results.xml --cov=com --cov-report=xml --cov-report=html
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-integration-test-results
        path: junit/integration-test-results.xml
      if: ${{ always() }}  # publish even when some tests fail
